package com.pharmasociale.models;

// Generated 26 juin 2015 11:47:43 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Beneficiaire generated by hbm2java
 */
public class Beneficiaire implements java.io.Serializable {

	private int idBeneficiaire;
	private Utilisateur utilisateur;
	private Set donDistribues = new HashSet(0);

	public Beneficiaire() {
	}

	public Beneficiaire(int idBeneficiaire) {
		this.idBeneficiaire = idBeneficiaire;
	}

	public Beneficiaire(int idBeneficiaire, Utilisateur utilisateur,
			Set donDistribues) {
		this.idBeneficiaire = idBeneficiaire;
		this.utilisateur = utilisateur;
		this.donDistribues = donDistribues;
	}

	public int getIdBeneficiaire() {
		return this.idBeneficiaire;
	}

	public void setIdBeneficiaire(int idBeneficiaire) {
		this.idBeneficiaire = idBeneficiaire;
	}

	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public Set getDonDistribues() {
		return this.donDistribues;
	}

	public void setDonDistribues(Set donDistribues) {
		this.donDistribues = donDistribues;
	}

}
