package com.pharmasociale.models;

// Generated 5 août 2015 12:19:05 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Beneficiaire generated by hbm2java
 */
public class Beneficiaire implements java.io.Serializable {

	private int idBeneficiaire;
	private Utilisateur utilisateur;
	private Set donAttribues = new HashSet(0);

	public Beneficiaire() {
	}

	public Beneficiaire(int idBeneficiaire) {
		this.idBeneficiaire = idBeneficiaire;
	}

	public Beneficiaire(int idBeneficiaire, Utilisateur utilisateur,
			Set donAttribues) {
		this.idBeneficiaire = idBeneficiaire;
		this.utilisateur = utilisateur;
		this.donAttribues = donAttribues;
	}

	public int getIdBeneficiaire() {
		return this.idBeneficiaire;
	}

	public void setIdBeneficiaire(int idBeneficiaire) {
		this.idBeneficiaire = idBeneficiaire;
	}

	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public Set getDonAttribues() {
		return this.donAttribues;
	}

	public void setDonAttribues(Set donAttribues) {
		this.donAttribues = donAttribues;
	}

}
