package com.pharmasociale.models;

// Generated 26 juin 2015 11:47:43 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DonDistribue generated by hbm2java
 */
public class DonDistribue implements java.io.Serializable {

	private int idDon;
	private Pharmacien pharmacien;
	private Beneficiaire beneficiaire;
	private String reference;
	private Date note;
	private Date createdAt;
	private Date upadatedAt;
	private Set medDistribs = new HashSet(0);

	public DonDistribue() {
	}

	public DonDistribue(int idDon) {
		this.idDon = idDon;
	}

	public DonDistribue(int idDon, Pharmacien pharmacien,
			Beneficiaire beneficiaire, String reference, Date note,
			Date createdAt, Date upadatedAt, Set medDistribs) {
		this.idDon = idDon;
		this.pharmacien = pharmacien;
		this.beneficiaire = beneficiaire;
		this.reference = reference;
		this.note = note;
		this.createdAt = createdAt;
		this.upadatedAt = upadatedAt;
		this.medDistribs = medDistribs;
	}

	public int getIdDon() {
		return this.idDon;
	}

	public void setIdDon(int idDon) {
		this.idDon = idDon;
	}

	public Pharmacien getPharmacien() {
		return this.pharmacien;
	}

	public void setPharmacien(Pharmacien pharmacien) {
		this.pharmacien = pharmacien;
	}

	public Beneficiaire getBeneficiaire() {
		return this.beneficiaire;
	}

	public void setBeneficiaire(Beneficiaire beneficiaire) {
		this.beneficiaire = beneficiaire;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public Date getNote() {
		return this.note;
	}

	public void setNote(Date note) {
		this.note = note;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpadatedAt() {
		return this.upadatedAt;
	}

	public void setUpadatedAt(Date upadatedAt) {
		this.upadatedAt = upadatedAt;
	}

	public Set getMedDistribs() {
		return this.medDistribs;
	}

	public void setMedDistribs(Set medDistribs) {
		this.medDistribs = medDistribs;
	}

}
