package com.pharmasociale.models;

// Generated 5 août 2015 12:19:05 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Donnateur generated by hbm2java
 */
public class Donnateur implements java.io.Serializable {

	private int idDonnateur;
	private Utilisateur utilisateur;
	private Set dons = new HashSet(0);

	public Donnateur() {
	}

	public Donnateur(int idDonnateur) {
		this.idDonnateur = idDonnateur;
	}

	public Donnateur(int idDonnateur, Utilisateur utilisateur, Set dons) {
		this.idDonnateur = idDonnateur;
		this.utilisateur = utilisateur;
		this.dons = dons;
	}

	public int getIdDonnateur() {
		return this.idDonnateur;
	}

	public void setIdDonnateur(int idDonnateur) {
		this.idDonnateur = idDonnateur;
	}

	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public Set getDons() {
		return this.dons;
	}

	public void setDons(Set dons) {
		this.dons = dons;
	}

}
