package com.pharmasociale.models;

// Generated 26 juin 2015 11:47:43 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Donnateur generated by hbm2java
 */
public class Donnateur implements java.io.Serializable {

	private int idDonnateur;
	private Utilisateur utilisateur;
	private Set donRecus = new HashSet(0);

	public Donnateur() {
	}

	public Donnateur(int idDonnateur) {
		this.idDonnateur = idDonnateur;
	}

	public Donnateur(int idDonnateur, Utilisateur utilisateur, Set donRecus) {
		this.idDonnateur = idDonnateur;
		this.utilisateur = utilisateur;
		this.donRecus = donRecus;
	}

	public int getIdDonnateur() {
		return this.idDonnateur;
	}

	public void setIdDonnateur(int idDonnateur) {
		this.idDonnateur = idDonnateur;
	}

	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public Set getDonRecus() {
		return this.donRecus;
	}

	public void setDonRecus(Set donRecus) {
		this.donRecus = donRecus;
	}

}
