package com.pharmasociale.models;

// Generated 5 août 2015 12:19:05 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * LigneDonAttribueId generated by hbm2java
 */
public class LigneDonAttribueId implements java.io.Serializable {

	private Integer idDon;
	private Integer idMedicament;
	private Integer qte;
	private Date dateExpiration;

	public LigneDonAttribueId() {
	}

	public LigneDonAttribueId(Integer idDon, Integer idMedicament, Integer qte,
			Date dateExpiration) {
		this.idDon = idDon;
		this.idMedicament = idMedicament;
		this.qte = qte;
		this.dateExpiration = dateExpiration;
	}

	public Integer getIdDon() {
		return this.idDon;
	}

	public void setIdDon(Integer idDon) {
		this.idDon = idDon;
	}

	public Integer getIdMedicament() {
		return this.idMedicament;
	}

	public void setIdMedicament(Integer idMedicament) {
		this.idMedicament = idMedicament;
	}

	public Integer getQte() {
		return this.qte;
	}

	public void setQte(Integer qte) {
		this.qte = qte;
	}

	public Date getDateExpiration() {
		return this.dateExpiration;
	}

	public void setDateExpiration(Date dateExpiration) {
		this.dateExpiration = dateExpiration;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LigneDonAttribueId))
			return false;
		LigneDonAttribueId castOther = (LigneDonAttribueId) other;

		return ((this.getIdDon() == castOther.getIdDon()) || (this.getIdDon() != null
				&& castOther.getIdDon() != null && this.getIdDon().equals(
				castOther.getIdDon())))
				&& ((this.getIdMedicament() == castOther.getIdMedicament()) || (this
						.getIdMedicament() != null
						&& castOther.getIdMedicament() != null && this
						.getIdMedicament().equals(castOther.getIdMedicament())))
				&& ((this.getQte() == castOther.getQte()) || (this.getQte() != null
						&& castOther.getQte() != null && this.getQte().equals(
						castOther.getQte())))
				&& ((this.getDateExpiration() == castOther.getDateExpiration()) || (this
						.getDateExpiration() != null
						&& castOther.getDateExpiration() != null && this
						.getDateExpiration().equals(
								castOther.getDateExpiration())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdDon() == null ? 0 : this.getIdDon().hashCode());
		result = 37
				* result
				+ (getIdMedicament() == null ? 0 : this.getIdMedicament()
						.hashCode());
		result = 37 * result
				+ (getQte() == null ? 0 : this.getQte().hashCode());
		result = 37
				* result
				+ (getDateExpiration() == null ? 0 : this.getDateExpiration()
						.hashCode());
		return result;
	}

}
