package com.pharmasociale.models;

// Generated 5 août 2015 12:19:05 by Hibernate Tools 4.0.0

/**
 * LigneDon generated by hbm2java
 */
public class LigneDon implements java.io.Serializable {

	private LigneDonId id;
	private Medicament medicament;
	private Don don;

	public LigneDon() {
	}

	public LigneDon(LigneDonId id) {
		this.id = id;
	}

	public LigneDon(LigneDonId id, Medicament medicament, Don don) {
		this.id = id;
		this.medicament = medicament;
		this.don = don;
	}

	public LigneDonId getId() {
		return this.id;
	}

	public void setId(LigneDonId id) {
		this.id = id;
	}

	public Medicament getMedicament() {
		return this.medicament;
	}

	public void setMedicament(Medicament medicament) {
		this.medicament = medicament;
	}

	public Don getDon() {
		return this.don;
	}

	public void setDon(Don don) {
		this.don = don;
	}

}
