package com.pharmasociale.models;

// Generated 5 août 2015 12:19:05 by Hibernate Tools 4.0.0

/**
 * LigneDonAttribue generated by hbm2java
 */
public class LigneDonAttribue implements java.io.Serializable {

	private LigneDonAttribueId id;
	private Medicament medicament;
	private DonAttribue donAttribue;

	public LigneDonAttribue() {
	}

	public LigneDonAttribue(LigneDonAttribueId id) {
		this.id = id;
	}

	public LigneDonAttribue(LigneDonAttribueId id, Medicament medicament,
			DonAttribue donAttribue) {
		this.id = id;
		this.medicament = medicament;
		this.donAttribue = donAttribue;
	}

	public LigneDonAttribueId getId() {
		return this.id;
	}

	public void setId(LigneDonAttribueId id) {
		this.id = id;
	}

	public Medicament getMedicament() {
		return this.medicament;
	}

	public void setMedicament(Medicament medicament) {
		this.medicament = medicament;
	}

	public DonAttribue getDonAttribue() {
		return this.donAttribue;
	}

	public void setDonAttribue(DonAttribue donAttribue) {
		this.donAttribue = donAttribue;
	}

}
