package com.pharmasociale.models;

// Generated 26 juin 2015 11:47:43 by Hibernate Tools 4.0.0

/**
 * MedDistrib generated by hbm2java
 */
public class MedDistrib implements java.io.Serializable {

	private MedDistribId id;
	private DonDistribue donDistribue;

	public MedDistrib() {
	}

	public MedDistrib(MedDistribId id) {
		this.id = id;
	}

	public MedDistrib(MedDistribId id, DonDistribue donDistribue) {
		this.id = id;
		this.donDistribue = donDistribue;
	}

	public MedDistribId getId() {
		return this.id;
	}

	public void setId(MedDistribId id) {
		this.id = id;
	}

	public DonDistribue getDonDistribue() {
		return this.donDistribue;
	}

	public void setDonDistribue(DonDistribue donDistribue) {
		this.donDistribue = donDistribue;
	}

}
