package com.pharmasociale.models;

// Generated 26 juin 2015 11:47:43 by Hibernate Tools 4.0.0

/**
 * MedDistribId generated by hbm2java
 */
public class MedDistribId implements java.io.Serializable {

	private Integer idDon;
	private Integer idMedicament;
	private Integer quantite;

	public MedDistribId() {
	}

	public MedDistribId(Integer idDon, Integer idMedicament, Integer quantite) {
		this.idDon = idDon;
		this.idMedicament = idMedicament;
		this.quantite = quantite;
	}

	public Integer getIdDon() {
		return this.idDon;
	}

	public void setIdDon(Integer idDon) {
		this.idDon = idDon;
	}

	public Integer getIdMedicament() {
		return this.idMedicament;
	}

	public void setIdMedicament(Integer idMedicament) {
		this.idMedicament = idMedicament;
	}

	public Integer getQuantite() {
		return this.quantite;
	}

	public void setQuantite(Integer quantite) {
		this.quantite = quantite;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MedDistribId))
			return false;
		MedDistribId castOther = (MedDistribId) other;

		return ((this.getIdDon() == castOther.getIdDon()) || (this.getIdDon() != null
				&& castOther.getIdDon() != null && this.getIdDon().equals(
				castOther.getIdDon())))
				&& ((this.getIdMedicament() == castOther.getIdMedicament()) || (this
						.getIdMedicament() != null
						&& castOther.getIdMedicament() != null && this
						.getIdMedicament().equals(castOther.getIdMedicament())))
				&& ((this.getQuantite() == castOther.getQuantite()) || (this
						.getQuantite() != null
						&& castOther.getQuantite() != null && this
						.getQuantite().equals(castOther.getQuantite())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdDon() == null ? 0 : this.getIdDon().hashCode());
		result = 37
				* result
				+ (getIdMedicament() == null ? 0 : this.getIdMedicament()
						.hashCode());
		result = 37 * result
				+ (getQuantite() == null ? 0 : this.getQuantite().hashCode());
		return result;
	}

}
