package com.pharmasociale.models;

// Generated 26 juin 2015 11:47:43 by Hibernate Tools 4.0.0

/**
 * MedRecu generated by hbm2java
 */
public class MedRecu implements java.io.Serializable {

	private MedRecuId id;
	private DonRecu donRecu;
	private Medicament medicament;

	public MedRecu() {
	}

	public MedRecu(MedRecuId id) {
		this.id = id;
	}

	public MedRecu(MedRecuId id, DonRecu donRecu, Medicament medicament) {
		this.id = id;
		this.donRecu = donRecu;
		this.medicament = medicament;
	}

	public MedRecuId getId() {
		return this.id;
	}

	public void setId(MedRecuId id) {
		this.id = id;
	}

	public DonRecu getDonRecu() {
		return this.donRecu;
	}

	public void setDonRecu(DonRecu donRecu) {
		this.donRecu = donRecu;
	}

	public Medicament getMedicament() {
		return this.medicament;
	}

	public void setMedicament(Medicament medicament) {
		this.medicament = medicament;
	}

}
