package com.pharmasociale.models;

// Generated 26 juin 2015 11:47:43 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Pharmacie generated by hbm2java
 */
public class Pharmacie implements java.io.Serializable {

	private int idPharmacie;
	private String enseigne;
	private String reference;
	private String adresse;
	private String ville;
	private Set utilisateurs = new HashSet(0);

	public Pharmacie() {
	}

	public Pharmacie(int idPharmacie) {
		this.idPharmacie = idPharmacie;
	}

	public Pharmacie(int idPharmacie, String enseigne, String reference,
			String adresse, String ville, Set utilisateurs) {
		this.idPharmacie = idPharmacie;
		this.enseigne = enseigne;
		this.reference = reference;
		this.adresse = adresse;
		this.ville = ville;
		this.utilisateurs = utilisateurs;
	}

	public int getIdPharmacie() {
		return this.idPharmacie;
	}

	public void setIdPharmacie(int idPharmacie) {
		this.idPharmacie = idPharmacie;
	}

	public String getEnseigne() {
		return this.enseigne;
	}

	public void setEnseigne(String enseigne) {
		this.enseigne = enseigne;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	public Set getUtilisateurs() {
		return this.utilisateurs;
	}

	public void setUtilisateurs(Set utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

}
