package com.pharmasociale.models;

// Generated 26 juin 2015 11:47:43 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Pharmacien generated by hbm2java
 */
public class Pharmacien implements java.io.Serializable {

	private int idPharmacien;
	private Integer id;
	private Set donDistribues = new HashSet(0);
	private Set donRecus = new HashSet(0);

	public Pharmacien() {
	}

	public Pharmacien(int idPharmacien) {
		this.idPharmacien = idPharmacien;
	}

	public Pharmacien(int idPharmacien, Integer id, Set donDistribues,
			Set donRecus) {
		this.idPharmacien = idPharmacien;
		this.id = id;
		this.donDistribues = donDistribues;
		this.donRecus = donRecus;
	}

	public int getIdPharmacien() {
		return this.idPharmacien;
	}

	public void setIdPharmacien(int idPharmacien) {
		this.idPharmacien = idPharmacien;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Set getDonDistribues() {
		return this.donDistribues;
	}

	public void setDonDistribues(Set donDistribues) {
		this.donDistribues = donDistribues;
	}

	public Set getDonRecus() {
		return this.donRecus;
	}

	public void setDonRecus(Set donRecus) {
		this.donRecus = donRecus;
	}

}
