package com.pharmasociale.models;

// Generated 5 août 2015 12:19:05 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;

/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur implements java.io.Serializable {

	@Id
	@SequenceGenerator(name="ID_GEN", sequenceName="NAME_OF_SEQ_IN_DB")
	@GeneratedValue(generator="ID_GEN")
	private int idUtilisateur;
	private String nom;
	private String prenom;
	private String userName;
	private String password;
	private Date birthday;
	private String adresse;
	private Date createdAt;
	private Date updatedAt;
	private Set pharmaciens = new HashSet(0);
	private Set donnateurs = new HashSet(0);
	private Set admins = new HashSet(0);
	private Set beneficiaires = new HashSet(0);

	public Utilisateur() {
	}

	public Utilisateur(int idUtilisateur, Date birthday, Date createdAt,
			Date updatedAt) {
		this.idUtilisateur = idUtilisateur;
		this.birthday = birthday;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Utilisateur(int idUtilisateur, String nom, String prenom,
			String userName, String password, Date birthday, String adresse,
			Date createdAt, Date updatedAt, Set pharmaciens, Set donnateurs,
			Set admins, Set beneficiaires) {
		this.idUtilisateur = idUtilisateur;
		this.nom = nom;
		this.prenom = prenom;
		this.userName = userName;
		this.password = password;
		this.birthday = birthday;
		this.adresse = adresse;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.pharmaciens = pharmaciens;
		this.donnateurs = donnateurs;
		this.admins = admins;
		this.beneficiaires = beneficiaires;
	}

	public int getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(int idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getPharmaciens() {
		return this.pharmaciens;
	}

	public void setPharmaciens(Set pharmaciens) {
		this.pharmaciens = pharmaciens;
	}

	public Set getDonnateurs() {
		return this.donnateurs;
	}

	public void setDonnateurs(Set donnateurs) {
		this.donnateurs = donnateurs;
	}

	public Set getAdmins() {
		return this.admins;
	}

	public void setAdmins(Set admins) {
		this.admins = admins;
	}

	public Set getBeneficiaires() {
		return this.beneficiaires;
	}

	public void setBeneficiaires(Set beneficiaires) {
		this.beneficiaires = beneficiaires;
	}

}
