package com.pharmasociale.models;

// Generated 26 juin 2015 11:47:43 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur implements java.io.Serializable {

	private int id;
	private Pharmacie pharmacie;
	private String nom;
	private String prenom;
	private String userName;
	private String password;
	private Date birthday;
	private String adresse;
	private Date createdAt;
	private Date updatedAt;
	private Set donnateurs = new HashSet(0);
	private Set beneficiaires = new HashSet(0);
	private Set admins = new HashSet(0);

	public Utilisateur() {
	}

	public Utilisateur(int id) {
		this.id = id;
	}

	public Utilisateur(int id, Pharmacie pharmacie, String nom, String prenom,
			String userName, String password, Date birthday, String adresse,
			Date createdAt, Date updatedAt, Set donnateurs, Set beneficiaires,
			Set admins) {
		this.id = id;
		this.pharmacie = pharmacie;
		this.nom = nom;
		this.prenom = prenom;
		this.userName = userName;
		this.password = password;
		this.birthday = birthday;
		this.adresse = adresse;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.donnateurs = donnateurs;
		this.beneficiaires = beneficiaires;
		this.admins = admins;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Pharmacie getPharmacie() {
		return this.pharmacie;
	}

	public void setPharmacie(Pharmacie pharmacie) {
		this.pharmacie = pharmacie;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getDonnateurs() {
		return this.donnateurs;
	}

	public void setDonnateurs(Set donnateurs) {
		this.donnateurs = donnateurs;
	}

	public Set getBeneficiaires() {
		return this.beneficiaires;
	}

	public void setBeneficiaires(Set beneficiaires) {
		this.beneficiaires = beneficiaires;
	}

	public Set getAdmins() {
		return this.admins;
	}

	public void setAdmins(Set admins) {
		this.admins = admins;
	}

}
